### PR TITLE
Fix various issues related to volume fade-in/fade-out functionality

### LINKED ISSUE #256: Issues with fade-in/fade-out
### Version
Latest

### Description
If you specify a fade-out duration, when you click Pause, the icon switches to "Pause" when the audio is completely faded (results in a ~1 sec lag, feels awkward). But it should change immediately after clicking it, regardless of the fade value.

### Reproduce Link
https://www.lijinke.cn/react-music-player/

### PR DESCRIPTION
**Pull request by JeffreyCA**
Fixes #256

### Issues addressed
- No more delay in pause/play button while fading out
- Fade ins always start from 0
- Remove fade-in when starting a track from the beginning (same as Spotify)
- If you have a long fade-in/fade-out duration and repeatedly click pause/play many times, audio no longer stutters and play/pause buttons are always responsive
    - I changed it so that if you pause in the middle of fading in or play in the middle of fading out, it stops the ongoing fade and starts a new fade (opposite direction)
- Volume bar no longer jumps when you adjust volume in the middle of a fade-in/fade-out
- Pressing "Play" while volume is muted no longer plays audio aloud
- If you are in the middle of a fade-in and you change the volume, the fade in interval re-calculates the deltas and continues transitioning to the new volume.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -1436,8 +1529,8 @@ export default class ReactJkMusicPlayer extends PureComponent {
 
   onAudioVolumeChange = () => {
     const { volume } = this.audio
-    const { isVolumeFadeChang } = this.state
-    if (isVolumeFadeChang) {
+    const { currentVolumeFade } = this.state
+    if (currentVolumeFade !== VOLUME_FADE.NONE) {
```
Comment (lijinke666) [inline src/index.js:1533]: image
image

Now. toggle play, will be trigger `onAudioVolumeChange`  i think this is a bug

Comment (JeffreyCA) [reply src/index.js:1533]: Thanks for catching it
